version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # volumes:
      # - postgres_data:/var/lib/postgresql/data
    ports:
      - ${HOST_PORT}:${DATABASE_PORT}

  app:
    build: .
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db


# volumes:
#   postgres_data: